version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQLDB_USER=root
      - MYSQL_DATABASE=online_book_store
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql

  web-api:
    depends_on:
      - mysqldb
    ports:
      - "8091:8091"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3307/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    build:
      context: .
      dockerfile: Dockerfile
#  app:
#    depends_on:
#      - mysqldb
#    build: ./bezkoder-app
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3307/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true

volumes:
  db: