
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_book_store
    username: appuser
    password: Alpha.02$
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-circular-references: true

app:
  isbn:
    prefix: 978
    length: 13
  seed:
    database: false
  security:
    authentication:
      basic:
        enable: true
        username: user
        password: password
      jwt:
        enable: false
        username: user
        password: password